version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  # Check for updates to GitHub Actions every week
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"  # Check for updates to Python packages every week
