name: 'Setup NCA environment'
description: 'Checks out NCA, then installs the required dependencies'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
    with:
      python-version: 3.8
      architecture: x64
      cache: pip
  - run: pip install -r requirements.txt
    shell: bash
