name: 'Setup NCA environment'
description: 'Checks out NCA, then installs the required dependencies'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236  # v4.7.1
    with:
      python-version: 3.8
      architecture: x64
      cache: pip
  - run: pip install -r requirements.txt
    shell: bash
