apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: k8s-netpol-report
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: "Kubernetes, Networking, Security"
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: "Kubernetes, NetworkPolicy"
    tekton.dev/platforms: "linux/amd64"
    tekton.dev/displayName: "K8s NetworkPolicy Connectivity Report"
spec:
  description: >-
    A task to produce a network-connectivity report of your K8s application
  params:
    - name: deployment-path
      type: string
      description: The path in the 'source' workspace where deployment yamls are
      default: .
    - name: netpol-path
      type: string
      description: The path in the 'source' workspace where the NetworkPolicy yamls are stored
      default: .
    - name: output-format
      type: string
      description: Connectivity report format (either "md", "yaml", "csv", "dot" or "txt")
      default: md
    - name: output-dir
      type: string
      description: The directory under 'source' workspace to write connectivity report file into.
      default: netpol-report-output-dir
  workspaces:
    - name: source
  results:
    - name: connectivity-report-file
      description: Path in 'sources' workspace of the connectivity report file
  steps:
    - name: make-result-dir # This step prepares the output directory, as NCA runs without root permissions.
      image: ubuntu
      workingDir: $(workspaces.source.path)
      env:
      - name: PARAMS_OUTPUT_DIR
        value: $(params.output-dir)
      script: |
        #!/bin/sh
        mkdir -p "$PARAMS_OUTPUT_DIR"
        chmod a+w "$PARAMS_OUTPUT_DIR"
    - name: produce-connectivity-report
      image: ghcr.io/np-guard/nca@sha256:027d750381811e0e2e0b6235dc471a13d56b57797c81a83efeffcb49e40f7914
      workingDir: $(workspaces.source.path)
      env:
      - name: PARAMS_OUTPUT_DIR
        value: $(params.output-dir)
      - name: PARAMS_OUTPUT_FORMAT
        value: $(params.output-format)
      - name: PARAMS_DEPLOYMENT_PATH
        value: $(params.deployment-path)
      - name: PARAMS_NETPOL_PATH
        value: $(params.netpol-path)
      script: |
        #!/bin/sh

        OUTFILE="$PARAMS_OUTPUT_DIR/connectivity_report.$PARAMS_OUTPUT_FORMAT"

        python /nca/nca.py \
          --connectivity "$PARAMS_NETPOL_PATH" \
          --pod_list "$PARAMS_DEPLOYMENT_PATH" \
          --ns_list "$PARAMS_DEPLOYMENT_PATH" \
          --output_format "$PARAMS_OUTPUT_FORMAT" \
          --file_out $OUTFILE

        printf '%s' "${OUTFILE}" | tee $(results.connectivity-report-file.path)
