apiVersion: v1
kind: Pod
metadata:
  name: istio-ingressgateway-livesim
  namespace: istio-ingressgateway-ns
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  serviceAccountName: istio-ingressgateway
  containers:
  - name: istio-proxy
    image: auto
---