name: Build and push NCA docker image

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set version
        run: |
          python GetVersionFromInput.py

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/ibm/nca

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
#          tags: ${{ steps.meta.outputs.tags }}
          tags: ghcr.io/ibm/nca:1.0
#          labels: ${{ steps.meta.outputs.labels }}