name: Build and push NCA docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version number'
        required: true
        default: 0.0.0

jobs:
  printInputs:
    echo "Build and release of NCA version ${{ github.event.inputs.version }}"

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: ghcr.io/ibm/nca:${{ github.event.inputs.version }}
