name: Build and push NCA docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'A build version number'
        required: true
        default: 0.0.0

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set version
        run: |
          echo "version=$(cat build_number.txt)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@v3
#        with:
#          images: ghcr.io/ibm/nca

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          tags: ghcr.io/ibm/nca:${{ env.version }}
          tags: ghcr.io/ibm/nca:${{ inputs.version }}
