name: Create docker release and github release

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    types: [closed]
    paths: ["nca/VERSION.txt"]

permissions:
  contents: read

jobs:
  push_to_registry:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    name: Push a Docker image to the Docker Hub and create a github release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup NCA environment
        uses: ./.github/actions/setup-nca-env

      - name: Set the version number
        run: |
          export VERSION=$(cat nca/VERSION.txt)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          push: true
          tags: ghcr.io/ibm/nca:${{ env.version }}

      - name: Build and push ubi-based Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          file: Dockerfile.ubi
          push: true
          tags: ghcr.io/ibm/nca:${{ env.version }}-ubi

      - name: Create and push a new git tag
        run: |
          git config user.name ${{ github.actor }}
          git tag -a v${{ env.version }} -m "Version ${{ env.version }}"
          git push origin v${{ env.version }}

      - name: Create a github release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          release_name: Release v${{ env.version }}
          body: |
            Changes in this Release:
          draft: false
          prerelease: false

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Push version to PyPi
        uses: pypa/gh-action-pypi-publish@5d1679fa6b895587c6eb10c3fe82205b440a580e
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
