name: Create docker release and github release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version number'
        required: true
        default: 0.0.0

permissions:
  contents: read

jobs:
  push_to_registry:
    name: Push a Docker image to the Docker Hub and create a github release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Print the version number
        run: |
          echo "Creating docker image and github release of the NCA version ${{ github.event.inputs.version }}"

      - name: Check out the repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Log in to Docker Hub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          tags: ghcr.io/ibm/nca:${{ github.event.inputs.version }}

      - name: Create and push a new git tag
        run: |
          git config user.name ${{ github.actor }}
          git tag -a v${{ github.event.inputs.version }} -m "Version ${{ github.event.inputs.version }}"
          git push origin v${{ github.event.inputs.version }}

      - name: Create a github release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          body: |
            Changes in this Release:
          draft: false
          prerelease: false