name: resets-tests-expected-runtime
on:
  workflow_dispatch: # manual triggering
jobs:
  reset_all_tests_runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-nca-env
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-push.yml
          workflow_conclusion: success
          name: run-alltests-log
          path: tests/
      - name: run script to update expected run time file
        run: python tests/update_expected_runtime.py --changed_tests ALL_TESTS
      - run: rm tests/run_log.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v8.0.2
        with:
          default_author: github_actions
          message: 'Updating the tests_expected_runtime.csv file'
