name: reset-tests-expected-runtime

on:
  workflow_dispatch: # manual triggering

permissions:
  actions: read
  contents: read

jobs:
  reset_all_tests_runtime:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: ./.github/actions/setup-nca-env
      - uses: dawidd6/action-download-artifact@7847792dd435a50521b8e3bd3576dae7459d1fa8
        with:
          workflow: test-push.yml
          workflow_conclusion: completed
          name: k8s-log
          path: tests/
      - uses: dawidd6/action-download-artifact@7847792dd435a50521b8e3bd3576dae7459d1fa8
        with:
          workflow: test-push.yml
          workflow_conclusion: completed
          name: calico-log
          path: tests/
      - uses: dawidd6/action-download-artifact@7847792dd435a50521b8e3bd3576dae7459d1fa8
        with:
          workflow: test-push.yml
          workflow_conclusion: completed
          name: istio-log
          path: tests/
      - name: run script to update expected run time for all tests
        run: |
          export PYTHONPATH=.
          python tests/update_expected_runtime.py --changed_tests ALL_TESTS
          rm tests/*_log.txt
      - name: Commit changes
        run: |
          git config user.name ${{ github.actor }}
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add tests/expected_runtime/calico_tests_expected_runtime.csv tests/expected_runtime/istio_tests_expected_runtime.csv tests/expected_runtime/k8s_tests_expected_runtime.csv
          git diff-index --quiet HEAD || ( git commit -m"Updating expected-runtime files" && git push )
