name: reset-tests-expected-runtime

on:
  workflow_dispatch: # manual triggering

permissions:
  actions: read
  contents: write

jobs:
  reset_all_tests_runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: ./.github/actions/setup-nca-env
      - uses: dawidd6/action-download-artifact@575b1e4167df67acf7e692af784566618b23c71e
        with:
          workflow: test-push.yml
          workflow_conclusion: success
          name: run-alltests-log
          path: tests/
      - name: run script to update expected run time for all tests
        run: |
          python tests/update_expected_runtime.py --changed_tests ALL_TESTS
          rm tests/run_log.txt
      - name: Commit changes
        run: |
          git config user.name ${{ github.actor }}
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add tests/tests_expected_runtime.csv
          git diff-index --quiet HEAD || ( git commit -m"Updating expected-runtimes file" && git push )
