name: test-push

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Build Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        id: build_docker
        with:
          context: .
          push: false
      - name: Check Docker image
        run: docker run ${{ steps.build_docker.outputs.digest }} -h
  test-docker-ubi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Build Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        id: build_docker
        with:
          context: .
          file: Dockerfile.ubi
          push: false
      - name: Check Docker image
        run: docker run ${{ steps.build_docker.outputs.digest }} -h
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./.github/actions/setup-nca-env
      - run: pip install flake8
      - name: Lint with flake8
        run: flake8 nca --count --max-complexity=15 --max-line-length=127 --statistics

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./.github/actions/setup-nca-env
      - run: |
          export PYTHONPATH=.
          python tests/run_unittests.py
  k8s-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./.github/actions/setup-nca-env
      - name: install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          sudo ./get_helm.sh
      - name: Run k8s tests
        env:
          GHE_TOKEN: ${{ github.token }}
          PYTHONPATH: .
        run: python tests/run_all_tests.py --type=general --category=k8s --check_run_time | tee tests/k8s_log.txt ; test ${PIPESTATUS[0]} -eq 0
      - name: upload run_k8s_tests log
        if: ${{ always() }}
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: k8s-log
          path: tests/k8s_log.txt
      - name: Upload k8s failed run-time tests file
        if: ${{ always() }}
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: k8s-failed-run-time-check-file
          path: ./tests/k8s_tests_failed_runtime_check.csv
          if-no-files-found: ignore
  calico-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./.github/actions/setup-nca-env
      - name: Run calico tests
        env:
          GHE_TOKEN: ${{ github.token }}
          PYTHONPATH: .
        run: python tests/run_all_tests.py --type=general --category=calico --check_run_time | tee tests/calico_log.txt ; test ${PIPESTATUS[0]} -eq 0
      - name: upload run_calico_tests log
        if: ${{ always() }}
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: calico-log
          path: tests/calico_log.txt
      - name: Upload calico failed run-time tests file
        if: ${{ always() }}
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: calico-failed-run-time-check-file
          path: ./tests/calico_tests_failed_runtime_check.csv
          if-no-files-found: ignore
  istio-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./.github/actions/setup-nca-env
      - name: Run istio tests
        env:
          GHE_TOKEN: ${{ github.token }}
          PYTHONPATH: .
        run: python tests/run_all_tests.py --type=general --category=istio --check_run_time | tee tests/istio_log.txt ; test ${PIPESTATUS[0]} -eq 0
      - name: upload run_istio_tests log
        if: ${{ always() }}
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: istio-log
          path: tests/istio_log.txt
      - name: Upload istio failed run-time tests file
        if: ${{ always() }}
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: istio-failed-run-time-check-file
          path: ./tests/istio_tests_failed_runtime_check.csv
          if-no-files-found: ignore
  fw-rules-assertion-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./.github/actions/setup-nca-env
      - run: |
          export PYTHONPATH=.
          python tests/run_all_tests.py --type=fw_rules_assertions
  live-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./.github/actions/setup-nca-env
      - uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00
      - run: |
          curl -L https://istio.io/downloadIstio | sh -
          cd istio-1.*
          export PATH=$PWD/bin:$PATH
          istioctl install --set profile=demo -y
      - run: |
          export PYTHONPATH=.
          python tests/run_all_tests.py --type=k8s_live_general
  rest-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./.github/actions/setup-nca-env
      - run: |
          python -m nca --daemon &
          NCA_PID=$!
          while true; do  # wait until REST server becomes responsive
            curl_status=0
            curl localhost:5000 || curl_status=$?
            [ $curl_status -gt 0 ]  || break
            sleep 1
          done
          curl -X POST -H Content-Type:application/json -d @tests/k8s_testcases/example_podlist/ns_list.json localhost:5000/namespace_list
          curl -X POST -H Content-Type:application/json -d @tests/k8s_testcases/example_podlist/pods_list.json localhost:5000/pod_list
          curl -X POST -H Content-Type:application/json -d @tests/k8s_testcases/example_policies/testcase1/testcase1-networkpolicy1.json localhost:5000/policy_sets
          curl localhost:5000/policy_sets/set_0/findings -o testcase1_findings.json
          diff testcase1_findings.json tests/rest_api/testcase1-findings.json
          kill $NCA_PID
