name: Test live k8s cluster

on:
#  push:
#    branches:
#      - master
#  pull_request:
  workflow_dispatch:

jobs:
  k8s-live-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Run live-k8s tests
        run: python tests/run_live_k8s_tests.py -i cmdline_live_k8s_tests.yaml
