name: test-push

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: 3.8
          architecture: x64

      - name: Build Docker image
        uses: docker/build-push-action@v2
        id: build_docker
        with:
          context: .
          push: false

      - name: Check Docker image
        run: docker run ${{ steps.build_docker.outputs.digest }} -h

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests
        run: python tests/run_unittests.py
      - name: Run all tests
        env:
          GHE_TOKEN: ${{ github.token }}
        run: python tests/run_all_tests.py --type=general
      - name: Run output comparison tests
        run:  python tests/run_all_tests.py --type=output
      - name: Run fw-rules assertions tests
        run:  python tests/run_all_tests.py --type=fw_rules_assertions
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
      - name: Run live-k8s tests
        run:  python tests/run_all_tests.py --type=k8s_live_general
