name: test-push

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        id: build_docker
        with:
          context: .
          push: false
      - name: Check Docker image
        run: docker run ${{ steps.build_docker.outputs.digest }} -h
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8
          architecture: x64
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests
        run: python tests/run_unittests.py
      - name: Run all tests
        env:
          GHE_TOKEN: ${{ github.token }}
        run: python tests/run_all_tests.py --type=general --check_run_time
      - name: Commit failed run time file
        uses: EndBug/add-and-commit@v8.0.1
        with:
          default_author: github_actions
          message: 'Adding Failed Run Time Check'
          add: '*.csv'
      - name: Run output comparison tests
        run:  python tests/run_all_tests.py --type=output
      - name: Run fw-rules assertions tests
        run:  python tests/run_all_tests.py --type=fw_rules_assertions
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
      - name: Run live-k8s tests
        run:  python tests/run_all_tests.py --type=k8s_live_general
