name: test-push

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        id: build_docker
        with:
          context: .
          push: false
      - name: Check Docker image
        run: docker run ${{ steps.build_docker.outputs.digest }} -h
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-nca-env
      - run: pip install flake8 pytest
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-nca-env
      - run: python tests/run_unittests.py
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-nca-env
      - name: Run all tests
        env:
          GHE_TOKEN: ${{ github.token }}
        run: python tests/run_all_tests.py --type=general --check_run_time | tee tests/run_log.txt
      - uses: actions/upload-artifact@v2
        with:
          name: run-alltests-log
          path: tests/run_log.txt
      - name: Upload failed run-time tests file
        uses: actions/upload-artifact@v2
        with:
          name: failed-run-time-check-file
          path: ./tests/tests_failed_runtime_check.csv
          if-no-files-found: ignore 
  fw-rules-assertion-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-nca-env
      - run:  python tests/run_all_tests.py --type=fw_rules_assertions
  live-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-nca-env
      - uses: helm/kind-action@v1.2.0
      - run:  python tests/run_all_tests.py --type=k8s_live_general
