name: update-tests-expected-runtime
on:
  pull_request: # for local testing
#  workflow_dispatch: # manual triggering , doesn't run on local branch
#  workflow_run: # doesn't run on local branch
#    workflows: [test-push]
#    types:
#      - completed
jobs:
  changed-tests:
    runs-on: ubuntu-latest
    outputs:
      changed_tests: ${{ steps.changes.outputs.changed_tests}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-nca-env
      - name: get added or modified tests
        id: changes
        run: |
          echo "::set-output name=changed_tests::$(((git fetch origin master:master) && (git diff --name-only --diff-filter=AMRD master)) | grep -E '*-scheme\.yaml|k8s_cmdline_tests.yaml' | xargs)"
  update-tests-runtime:
    runs-on: ubuntu-latest
    needs: changed-tests
    if: ${{needs.changed-tests.outputs.changed_tests}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-nca-env
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-push.yml
          workflow_conclusion: success
          name: run-alltests-log
          path: tests/
          search_artifacts: true #for testing
      - name: run script to update expected run time
        run: python tests/update_expected_runtime.py --changed_tests ${{needs.changed-tests.outputs.changed_tests}}
      - run: rm tests/run_log.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v8.0.2
        with:
          default_author: github_actions
          message: 'Updating the tests_expected_runtime.csv file'
          push: false # for testing

