name: update-tests-expected-output

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-nca-env
      - name: update expected output files
        run:  python tests/run_all_tests.py --type=output --action=override_expected_output
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Updating tests expected output files'
