name: update-tests-expected-output

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-nca-env
      - name: update or add expected output files
        run:  python tests/run_all_tests.py --type=general --override_expected_output_files --create_expected_output_files
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Updating and Adding tests expected output files'

