name: update-tests-expected-runtime
on:
  pull_request: # for local testing
  workflow_run: # works only on master branch
    workflows: [test-push]
    types:
      - completed
  workflow_dispatch: # manual triggering , runs only on master branch too

jobs:
  changed-tests:
    runs-on: ubuntu-latest
    outputs:
      changed_tests: ${{ steps.changes.outputs.changed_tests}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-nca-env
      - name: get added or modified tests
        id: changes
        run: |
          echo "::set-output name=changed_tests::$((git fetch origin master:master) && (git diff --name-only --diff-filter=ACRM master))"
  run-log:

  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changed-tests
    # only run there are changed files
    if: ${{needs.changed-tests.outputs.changed_tests}}
    steps:
      - name: echo changed files
        run: echo ${{needs.changed-tests.outputs.changed_tests}}
