name: update-tests-expected-output

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: ./.github/actions/setup-nca-env
      - name: update or add expected output files
        run:  python tests/run_all_tests.py --type=general --override_expected_output_files --create_expected_output_files
        env:
          GHE_TOKEN: ${{ github.token }}
      - name: Commit changes
        run: |
          git config user.name ${{ github.actor }}
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add tests
          git diff-index --quiet HEAD || ( git commit -m"Updating and Adding tests expected output files" && git push )

