name: update-tests-expected-runtime
on:
  #workflow_dispatch: # manual triggering , runs only on master branch
  pull_request: # for local testing
  workflow_run:
    workflows: [test-push]
    types:
      - completed
    branches:
      - 'issue_134_b_mechanism_to_update_run_time'

jobs:
  changed-tests:
    runs-on: ubuntu-latest
    outputs:
      changed_tests: ${{ steps.changes.outputs.changed_tests}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-nca-env
      - name: get added or modified tests
        id: changes
        run: |
          echo "::set-output name=changed_tests::$(((git fetch origin master:master) && (git diff --name-only --diff-filter=ACRM master))| grep -e *-scheme.yaml -e *_cmdline_tests.yaml)"
#        with:
#          PATTERNS: |
#            tests/**/*-scheme.yaml
#          FILES: |
#            tests/k8s_cmdline_tests.yaml
#      - run: echo ${{ env.GIT_DIFF }}

