name: update-tests-expected-runtime

on:
#  # push is only for testing
#  push:
#    branches:
#      - issue_134_b_mechanism_to_update_run_time
  workflow_dispatch:

jobs:
  changedtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-nca-env
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            tests/**/*-scheme.yaml
          FILES: |
            tests/k8s_cmdline_tests.yaml
      - run: echo ${{ env.GIT_DIFF }}
