name: update-tests-expected-runtime

on:
  workflow_dispatch: # manual triggering

permissions:
  actions: read
  contents: read

jobs:
  changed-tests:
    runs-on: ubuntu-latest
    outputs:
      changed_tests: ${{ steps.changes.outputs.changed_tests}}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-nca-env
      - name: get added or modified tests
        id: changes
        run: |
          echo "::set-output name=changed_tests::$(((git fetch origin master:master) && (git diff --name-only --diff-filter=AMRD master)) | grep -E '*-scheme\.yaml|k8s_cmdline_tests.yaml' | xargs)"
  update-tests-runtime:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: changed-tests
    if: ${{needs.changed-tests.outputs.changed_tests}}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/setup-nca-env
      - uses: dawidd6/action-download-artifact@6765a42d86407a3d532749069ac03705ad82ebc6
        with:  # download all artifacts
          workflow: test-push.yml
          workflow_conclusion: completed
          path: tests/
      - name: run script to update expected run time
        run: |
          python tests/update_expected_runtime.py --changed_tests ${{needs.changed-tests.outputs.changed_tests}}
          rm tests/*_log.txt
          rm test/*_tests_failed_runtime_check.csv
      - name: Commit changes
        run: |
          git config user.name ${{ github.actor }}
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add tests/expected_runtime/calico_tests_expected_runtime.csv tests/expected_runtime/istio_tests_expected_runtime.csv tests/expected_runtime/k8s_tests_expected_runtime.csv
          git diff-index --quiet HEAD || ( git commit -m"Updating expected-runtimes file" && git push )
