name: update-tests-expected-runtime

on:
  workflow_dispatch:

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      changed_tests: ${{ steps.changes.outputs.changed_tests}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-nca-env
      - name: get added or modified tests
        id: changes
        echo "::set-output name=changed_tests::$(git diff 'tests/**/*-scheme.yaml' 'tests/k8s_cmdline_tests.yaml' --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }} ${{ github.sha }})"
  lint:
    runs-on: ubuntu-latest
      needs: changedfiles
      if: ${{needs.changedfiles.outputs.changed_tests}}
      steps:
        - name: echo changed tests
          run: echo ${{needs.changedfiles.outputs.changed_tests}}